{
 "title": "Retake Exam",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (instance) (node_cpu_seconds_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Free Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (instance) (node_memory_MemFree_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Docker",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (engine_daemon_container_states_containers)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}