global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['prometheus:9090']
  - job_name: 'docker'
    static_configs:
    - targets: ['192.168.99.122:9323']
  - job_name: 'node-exporter'
    static_configs:
    - targets: ['192.168.99.121:9100', '192.168.99.122:9100']
